# Datasource configuration in pdn environment
server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${HOST}:${PORT}/${DBNAME}
    driver-class-name: org.postgresql.Driver
    username: ${USER}
    password: ${PASS}
    hikari:
      idle-timeout: 10000
      pool-name: ApiPool
      maximum-pool-size: 5

custom:
  jwt:
    secret:
      key: b08c3d528d8a0fd6d013cf9b8af36e4680cdd3a13a6d70c4b7b25a792d1ec476
    expire:
      time: 1800000

logging:
  level:
    root: info
    org.springframework: info