# Server properties
server:
  servlet:
    context-path: /daily-book-api
# Spring properties
spring:
  # Dev is active by default. This value can be overwritten by java arg param 
  profiles:
    active: dev
  application:
    name: daily-book-api
  messages:
    basename: bundles/apiLanguageBundle
  jackson:
    serialization:
      write-dates-as-timestamps: false
springdoc:
  swagger-ui:
    enabled: true

